version: "3.9"
services:
  todo-server:
    build: .
    restart: always
    environment:
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: postgres
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - todolist-data:/var/lib/postgresql/data
  dbadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.de
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    volumes:
      - todolist-data:/var/lib/pgadmin
volumes:
  todolist-data:
  dbadmin-data: